In [2]:
# Import your pipeline modules here
# cut las to tiles
from musac_las_classifier.preprocessing.slicing_las_python import main_not_parallel_cut_tiles
# transform data to tensors
from musac_las_classifier.preprocessing.transformation_las2npy import main_not_parallel_transform_to_tensor
# predition
from predictor_multiclass_segmentation.predict_multiclass_segmentation import main_prediction
# 


In [11]:
las_directory = r'example_data/las'
las_cut_directory = r'example_data/las_cut'
main_not_parallel_cut_tiles(las_directory, las_cut_directory, tile_size=250)

['446_3972.las']
Saved example_data/las_cut\446_3972_446000_3972000.las
Saved example_data/las_cut\446_3972_446000_3972250.las
Saved example_data/las_cut\446_3972_446000_3972500.las
Saved example_data/las_cut\446_3972_446000_3972750.las
Saved example_data/las_cut\446_3972_446250_3972000.las
Saved example_data/las_cut\446_3972_446250_3972250.las
Saved example_data/las_cut\446_3972_446250_3972500.las
Saved example_data/las_cut\446_3972_446250_3972750.las
Saved example_data/las_cut\446_3972_446500_3972000.las
Saved example_data/las_cut\446_3972_446500_3972250.las
Saved example_data/las_cut\446_3972_446500_3972500.las
Saved example_data/las_cut\446_3972_446500_3972750.las
Saved example_data/las_cut\446_3972_446750_3972000.las
Saved example_data/las_cut\446_3972_446750_3972250.las
Saved example_data/las_cut\446_3972_446750_3972500.las
Saved example_data/las_cut\446_3972_446750_3972750.las


In [12]:
# configurations for transformation
import musac_las_classifier.preprocessing.config_preprocessing as cp


tensor_directory =  r'example_data/tensor'
main_not_parallel_transform_to_tensor(
    las_cut_directory, tensor_directory,
    cp.feature_input_tensor, cp.feature_output_tensor,
    cp.num_points_lim, cp.M_tensor_size, cp.K_nn
)

max_colour channel = 48896
min_colour channel = 6912
file 446_3972_446000_3972000.las is processing
shape: (512, 512, 4, 7)
len feature: 7
D= 7
[[[2. 3. 3. 3.]
  [2. 3. 3. 3.]
  [2. 3. 3. 3.]
  ...
  [3. 3. 2. 2.]
  [3. 2. 3. 2.]
  [3. 2. 3. 2.]]

 [[2. 3. 3. 3.]
  [2. 3. 3. 3.]
  [2. 3. 3. 2.]
  ...
  [3. 2. 3. 2.]
  [3. 2. 3. 2.]
  [3. 2. 3. 2.]]

 [[2. 3. 3. 3.]
  [2. 3. 3. 3.]
  [2. 3. 3. 3.]
  ...
  [2. 3. 3. 2.]
  [2. 3. 3. 2.]
  [2. 3. 3. 2.]]

 ...

 [[3. 4. 3. 3.]
  [3. 3. 3. 4.]
  [3. 3. 3. 4.]
  ...
  [3. 3. 3. 3.]
  [3. 3. 3. 3.]
  [3. 3. 3. 3.]]

 [[3. 3. 3. 4.]
  [3. 3. 3. 4.]
  [3. 3. 3. 3.]
  ...
  [3. 3. 3. 3.]
  [3. 3. 3. 3.]
  [3. 3. 3. 3.]]

 [[3. 3. 3. 4.]
  [3. 3. 3. 3.]
  [3. 3. 3. 3.]
  ...
  [3. 3. 3. 3.]
  [3. 3. 3. 3.]
  [3. 3. 3. 3.]]]
max_colour channel = 57088
min_colour channel = 3584
file 446_3972_446000_3972250.las is processing
shape: (512, 512, 4, 7)
len feature: 7
D= 7
[[[3. 3. 2. 2.]
  [3. 3. 2. 2.]
  [3. 3. 2. 2.]
  ...
  [2. 3. 2. 2.]
  [2. 3. 2. 

In [3]:
# configurations for transformation
import musac_las_classifier.preprocessing.config_preprocessing as cp
from musac_las_classifier.preprocessing.image_generator import main_not_parallel_tensor_to_image

tensor_directory =  r'example_data/tensor'
img_features_directory = r'example_data/img_features'
main_not_parallel_tensor_to_image(
    tensor_directory, img_features_directory,
    cp.feature_output_tensor, cp.channels_visualisation
)

channel feature 0
255.0
0.0
channel feature 1
255.0
0.0
channel feature 2
255.0
15.410401
channel feature 0
255.0
0.0
channel feature 1
255.0
0.0
channel feature 2
255.0
3.325624
channel feature 0
255.0
0.0
channel feature 1
255.0
0.0
channel feature 2
255.0
3.52084
channel feature 0
255.0
0.0
channel feature 1
255.0
0.0
channel feature 2
255.0
8.807933
channel feature 0
255.0
0.0
channel feature 1
255.0
0.0
channel feature 2
255.0
17.715513
channel feature 0
255.0
0.0
channel feature 1
255.0
0.0
channel feature 2
255.0
13.626172
channel feature 0
255.0
0.0
channel feature 1
255.0
0.0
channel feature 2
255.0
17.997255
channel feature 0
255.0
0.0
channel feature 1
255.0
0.0
channel feature 2
255.0
6.5364738
channel feature 0
255.0
0.0
channel feature 1
255.0
0.0
channel feature 2
255.0
5.4585476
channel feature 0
255.0
0.0
channel feature 1
255.0
0.0
channel feature 2
255.0
8.678231
channel feature 0
255.0
0.0
channel feature 1
255.0
0.0
channel feature 2
255.0
22.026024
channel feature

In [ ]:
#config for model prediction
import musac_las_classifier.predictor_multiclass_segmentation.config_prediction as cpred
# predition
from musac_las_classifier.predictor_multiclass_segmentation.predict_multiclass_segmentation import main_prediction

img_features_directory = r'example_data/img_features'
img_multiclass_directory = r'example_data/img_predict_multicalss'
main_prediction(img_features_directory, img_multiclass_directory, cpred.checkpoint_path)

output_dir: example_data/img_predict_multicalss
i here
save dir: example_data/img_predict_multicalss
dataloader: <torch.utils.data.dataloader.DataLoader object at 0x000001B7F141C070>
images:
save_dir: example_data/img_predict_multicalss\446_3972_446000_3972000.png
save_dir: example_data/img_predict_multicalss\446_3972_446000_3972250.png
save_dir: example_data/img_predict_multicalss\446_3972_446000_3972500.png
save_dir: example_data/img_predict_multicalss\446_3972_446000_3972750.png
save_dir: example_data/img_predict_multicalss\446_3972_446250_3972000.png
save_dir: example_data/img_predict_multicalss\446_3972_446250_3972250.png
save_dir: example_data/img_predict_multicalss\446_3972_446250_3972500.png
save_dir: example_data/img_predict_multicalss\446_3972_446250_3972750.png
images:
save_dir: example_data/img_predict_multicalss\446_3972_446500_3972000.png
save_dir: example_data/img_predict_multicalss\446_3972_446500_3972250.png
save_dir: example_data/img_predict_multicalss\446_3972_446500

In [5]:
from musac_las_classifier.postprocessing.join_img import main_join_img


img_multiclass_directory = r'example_data/img_predict_multicalss'
img_multiclass_join_directory = r'example_data/img_predict_multicalss_join'

main_join_img(img_multiclass_directory, img_multiclass_join_directory)

Stitching rows: 100%|██████████| 4/4 [00:00<00:00, 15.03it/s]


Stitched image saved as 'example_data/img_predict_multicalss_join\joined.png'


In [ ]:
from musac_las_classifier.generate_colored_las_3D.generate_colored_las_3D import mask_to_las_with_class_nn_rgb
import musac_las_classifier.generate_colored_las_3D.config_colored_las as ccl
import os


las_directory = r'example_data/las/446_3972.las'
img_multiclass_join_directory = r'example_data/img_predict_multicalss_join/joined.png'

outputdir = r'example_data/output_las_colored/446_3972.las'
outputfile = r'446_3972.las'

os.makedirs(outputdir, exist_ok=True)
las_output_colored_directory = os.path.join(outputdir,outputfile)

mask_to_las_with_class_nn_rgb(
    las_file_path=las_directory,
    image_file_path=img_multiclass_join_directory,
    output_las_path=las_output_colored_directory,
    class_colors=ccl.class_colors
)

File example_data/output_las_colored/446_3972.las\446_3972.las successfully created with point classes and RGB values.


In [ ]:
from generate_colored_las_3D.generate_class_las_3D import mask_to_las_with_class_only